### ISSUE TITLE
Return MIT License to Priority Queue

### ISSUE THREAD

**Issue by davecom** [bbvch13531/SwiftTemplateLibrary#1]
You stripped out the MIT License from my project (SwiftPriorityQueue) which you copied into this repository. You're not allowed to do that. If you copied files from other people's projects into this repository, you should restore their licenses as well. You should also put all of the other projects' licenses into your LICENSE file for the whole repository.

**Comment by bbvch13531** [comment]
Hello Kopec! Thank you for openning an issue in my repo! It's great honor to me making a conversation with you. :smile: 

First, It is all my mistake not including other licenses in my repo. I just realized it.Thanks for your advice.
I'll right add licenses in my LICENSE file.

Thank you again for let me know this issue. :+1:
